// <auto-generated />
using System.Reflection;

[assembly: AssemblyProduct("RegexLib")]
[assembly: AssemblyCopyright("Copyright © 2019 John Gietzen")]
[assembly: System.Runtime.InteropServices.ComVisible(false)]
