// <auto-generated />
using System;
using System.Reflection;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

[assembly: AssemblyTitle("RegexLib.Tests")]
[assembly: AssemblyDescription("A library for creating, consuming, and inspecting regular expressions.")]
[assembly: AssemblyConfiguration("")]
[assembly: AssemblyCompany("John Gietzen")]
[assembly: AssemblyProduct("RegexLib.Tests")]
[assembly: AssemblyCopyright("Copyright © John Gietzen 2012")]
[assembly: AssemblyTrademark("")]
[assembly: AssemblyCulture("")]

[assembly: CLSCompliant(true)]

[assembly: ComVisible(false)]

[assembly: Guid("ae986f0a-a244-46ad-89ea-8962dadf548a")]

[assembly: AssemblyVersion("1.0.0.0")]
[assembly: AssemblyFileVersion("1.0.0.0")]
