// <auto-generated />
using System;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

[assembly: Guid("f0e5ade3-a79d-46c8-86bf-abb5a7bd64b7")]
[assembly: CLSCompliant(true)]
[assembly: InternalsVisibleTo("RegexLib.Tests")]
