//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 3.4
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// $ANTLR 3.4 JavaScriptRegExp__.g 2012-07-09 23:07:32

// The variable 'variable' is assigned but its value is never used.
#pragma warning disable 219
// Unreachable code detected.
#pragma warning disable 162
// Missing XML comment for publicly visible type or member 'Type_or_Member'
#pragma warning disable 1591
// CLS compliance checking will not be performed on 'type' because it is not visible from outside this assembly.
#pragma warning disable 3019


using System.Collections.Generic;
using Antlr.Runtime;
using Antlr.Runtime.Misc;

namespace  RegexLib.Parsers.JavaScript 
{
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "3.4")]
[System.CLSCompliant(false)]
public partial class JavaScriptRegExpLexer : Antlr.Runtime.Lexer
{
	public const int EOF=-1;
	public const int T__4=4;

    // delegates
    // delegators

	public JavaScriptRegExpLexer()
	{
		OnCreated();
	}

	public JavaScriptRegExpLexer(ICharStream input )
		: this(input, new RecognizerSharedState())
	{
	}

	public JavaScriptRegExpLexer(ICharStream input, RecognizerSharedState state)
		: base(input, state)
	{

		OnCreated();
	}
	public override string GrammarFileName { get { return "JavaScriptRegExp__.g"; } }


	partial void OnCreated();
	partial void EnterRule(string ruleName, int ruleIndex);
	partial void LeaveRule(string ruleName, int ruleIndex);

	partial void EnterRule_T__4();
	partial void LeaveRule_T__4();

	// $ANTLR start "T__4"
	[GrammarRule("T__4")]
	private void mT__4()
	{
		EnterRule_T__4();
		EnterRule("T__4", 1);
		TraceIn("T__4", 1);
		try
		{
			int _type = T__4;
			int _channel = DefaultTokenChannel;
			// JavaScriptRegExp__.g:9:6: ( 'a' )
			DebugEnterAlt(1);
			// JavaScriptRegExp__.g:9:8: 'a'
			{
			DebugLocation(9, 8);
			Match('a'); 

			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("T__4", 1);
			LeaveRule("T__4", 1);
			LeaveRule_T__4();
		}
	}
	// $ANTLR end "T__4"

	public override void mTokens()
	{
		// JavaScriptRegExp__.g:1:8: ( T__4 )
		DebugEnterAlt(1);
		// JavaScriptRegExp__.g:1:10: T__4
		{
		DebugLocation(1, 10);
		mT__4(); 

		}


	}


	#region DFA

	protected override void InitDFAs()
	{
		base.InitDFAs();
	}

 
	#endregion

}

} // namespace  RegexLib.Parsers.JavaScript 
