// -----------------------------------------------------------------------
// <auto-generated>
// This code was generated by Pegasus 1.0.0.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
// -----------------------------------------------------------------------

namespace RegexLib.Parsers.JavaScript
{
    using System;
    using System.Collections.Generic;
    using Pegasus.Common;
    using System.Globalization;

    [System.CodeDom.Compiler.GeneratedCode("Pegasus", "1.0.0.0")]
    internal partial class JavaScriptRegExpParser
    {

    private static HashSet<UnicodeCategory> unicodeLetterCategories = new HashSet<UnicodeCategory>
    {
        UnicodeCategory.UppercaseLetter,
        UnicodeCategory.LowercaseLetter,
        UnicodeCategory.TitlecaseLetter,
        UnicodeCategory.ModifierLetter,
        UnicodeCategory.OtherLetter,
        UnicodeCategory.LetterNumber,
    };

    private static HashSet<UnicodeCategory> unicodeCombiningMarkCategories = new HashSet<UnicodeCategory>
    {
        UnicodeCategory.NonSpacingMark,
        UnicodeCategory.SpacingCombiningMark,
    };

    private static HashSet<UnicodeCategory> unicodeDigitCategories = new HashSet<UnicodeCategory>
    {
        UnicodeCategory.DecimalDigitNumber,
    };

    private static HashSet<UnicodeCategory> unicodeConnectorPunctuationCategories = new HashSet<UnicodeCategory>
    {
        UnicodeCategory.ConnectorPunctuation,
    };


        public string Parse(string subject, string fileName = null)
        {
            var cursor = new Cursor(subject, 0, fileName);
            var result = this.Pattern(ref cursor);
            if (result == null)
            {
                throw ExceptionHelper(cursor, () => "Failed to parse 'Pattern'.");
            }
            return result.Value;
        }

        private IParseResult<string> Pattern(ref Cursor cursor)
        {
            IParseResult<string> r0 = null;
            r0 = this.Disjunction(ref cursor);
            return r0;
        }

        private IParseResult<string> Disjunction(ref Cursor cursor)
        {
            IParseResult<string> r0 = null;
            if (r0 == null)
            {
                var startCursor0 = cursor;
                IParseResult<string> r1 = null;
                r1 = this.Alternative(ref cursor);
                if (r1 != null)
                {
                    IParseResult<string> r2 = null;
                    r2 = this.ParseLiteral(ref cursor, "|");
                    if (r2 != null)
                    {
                        IParseResult<string> r3 = null;
                        r3 = this.Disjunction(ref cursor);
                        if (r3 != null)
                        {
                            var len = cursor.Location - startCursor0.Location;
                            r0 = new ParseResult<string>(startCursor0, cursor, cursor.Subject.Substring(startCursor0.Location, len));
                        }
                        else
                        {
                            cursor = startCursor0;
                        }
                    }
                    else
                    {
                        cursor = startCursor0;
                    }
                }
                else
                {
                    cursor = startCursor0;
                }
            }
            if (r0 == null)
            {
                r0 = this.Alternative(ref cursor);
            }
            return r0;
        }

        private IParseResult<string> Alternative(ref Cursor cursor)
        {
            IParseResult<string> r0 = null;
            if (r0 == null)
            {
                var startCursor0 = cursor;
                IParseResult<string> r1 = null;
                r1 = this.Term(ref cursor);
                if (r1 != null)
                {
                    IParseResult<string> r2 = null;
                    r2 = this.Alternative(ref cursor);
                    if (r2 != null)
                    {
                        var len = cursor.Location - startCursor0.Location;
                        r0 = new ParseResult<string>(startCursor0, cursor, cursor.Subject.Substring(startCursor0.Location, len));
                    }
                    else
                    {
                        cursor = startCursor0;
                    }
                }
                else
                {
                    cursor = startCursor0;
                }
            }
            if (r0 == null)
            {
                r0 = this.Term(ref cursor);
            }
            return r0;
        }

        private IParseResult<string> Term(ref Cursor cursor)
        {
            IParseResult<string> r0 = null;
            if (r0 == null)
            {
                r0 = this.Assertion(ref cursor);
            }
            if (r0 == null)
            {
                var startCursor0 = cursor;
                IParseResult<string> r1 = null;
                r1 = this.Atom(ref cursor);
                if (r1 != null)
                {
                    IParseResult<IList<string>> r2 = null;
                    var startCursor1 = cursor;
                    var l0 = new List<string>();
                    while (l0.Count < 1)
                    {
                        IParseResult<string> r3 = null;
                        r3 = this.Quantifier(ref cursor);
                        if (r3 != null)
                        {
                            l0.Add(r3.Value);
                        }
                        else
                        {
                            break;
                        }
                    }
                    if (l0.Count >= 0)
                    {
                        r2 = new ParseResult<IList<string>>(startCursor1, cursor, l0.AsReadOnly());
                    }
                    else
                    {
                        cursor = startCursor1;
                    }
                    if (r2 != null)
                    {
                        var len = cursor.Location - startCursor0.Location;
                        r0 = new ParseResult<string>(startCursor0, cursor, cursor.Subject.Substring(startCursor0.Location, len));
                    }
                    else
                    {
                        cursor = startCursor0;
                    }
                }
                else
                {
                    cursor = startCursor0;
                }
            }
            return r0;
        }

        private IParseResult<string> Assertion(ref Cursor cursor)
        {
            IParseResult<string> r0 = null;
            if (r0 == null)
            {
                r0 = this.ParseLiteral(ref cursor, "^");
            }
            if (r0 == null)
            {
                r0 = this.ParseLiteral(ref cursor, "$");
            }
            if (r0 == null)
            {
                r0 = this.ParseLiteral(ref cursor, "\b");
            }
            if (r0 == null)
            {
                r0 = this.ParseLiteral(ref cursor, "B");
            }
            if (r0 == null)
            {
                var startCursor0 = cursor;
                IParseResult<string> r1 = null;
                r1 = this.ParseLiteral(ref cursor, "(?=");
                if (r1 != null)
                {
                    IParseResult<string> r2 = null;
                    r2 = this.Disjunction(ref cursor);
                    if (r2 != null)
                    {
                        IParseResult<string> r3 = null;
                        r3 = this.ParseLiteral(ref cursor, ")");
                        if (r3 != null)
                        {
                            var len = cursor.Location - startCursor0.Location;
                            r0 = new ParseResult<string>(startCursor0, cursor, cursor.Subject.Substring(startCursor0.Location, len));
                        }
                        else
                        {
                            cursor = startCursor0;
                        }
                    }
                    else
                    {
                        cursor = startCursor0;
                    }
                }
                else
                {
                    cursor = startCursor0;
                }
            }
            if (r0 == null)
            {
                var startCursor1 = cursor;
                IParseResult<string> r4 = null;
                r4 = this.ParseLiteral(ref cursor, "(?!");
                if (r4 != null)
                {
                    IParseResult<string> r5 = null;
                    r5 = this.Disjunction(ref cursor);
                    if (r5 != null)
                    {
                        IParseResult<string> r6 = null;
                        r6 = this.ParseLiteral(ref cursor, ")");
                        if (r6 != null)
                        {
                            var len = cursor.Location - startCursor1.Location;
                            r0 = new ParseResult<string>(startCursor1, cursor, cursor.Subject.Substring(startCursor1.Location, len));
                        }
                        else
                        {
                            cursor = startCursor1;
                        }
                    }
                    else
                    {
                        cursor = startCursor1;
                    }
                }
                else
                {
                    cursor = startCursor1;
                }
            }
            return r0;
        }

        private IParseResult<string> Quantifier(ref Cursor cursor)
        {
            IParseResult<string> r0 = null;
            var startCursor0 = cursor;
            IParseResult<string> r1 = null;
            r1 = this.QuantifierPrefix(ref cursor);
            if (r1 != null)
            {
                IParseResult<IList<string>> r2 = null;
                var startCursor1 = cursor;
                var l0 = new List<string>();
                while (l0.Count < 1)
                {
                    IParseResult<string> r3 = null;
                    r3 = this.ParseLiteral(ref cursor, "?");
                    if (r3 != null)
                    {
                        l0.Add(r3.Value);
                    }
                    else
                    {
                        break;
                    }
                }
                if (l0.Count >= 0)
                {
                    r2 = new ParseResult<IList<string>>(startCursor1, cursor, l0.AsReadOnly());
                }
                else
                {
                    cursor = startCursor1;
                }
                if (r2 != null)
                {
                    var len = cursor.Location - startCursor0.Location;
                    r0 = new ParseResult<string>(startCursor0, cursor, cursor.Subject.Substring(startCursor0.Location, len));
                }
                else
                {
                    cursor = startCursor0;
                }
            }
            else
            {
                cursor = startCursor0;
            }
            return r0;
        }

        private IParseResult<string> QuantifierPrefix(ref Cursor cursor)
        {
            IParseResult<string> r0 = null;
            if (r0 == null)
            {
                r0 = this.ParseLiteral(ref cursor, "*");
            }
            if (r0 == null)
            {
                r0 = this.ParseLiteral(ref cursor, "+");
            }
            if (r0 == null)
            {
                r0 = this.ParseLiteral(ref cursor, "?");
            }
            if (r0 == null)
            {
                var startCursor0 = cursor;
                IParseResult<string> r1 = null;
                r1 = this.ParseLiteral(ref cursor, "{");
                if (r1 != null)
                {
                    IParseResult<IList<string>> r2 = null;
                    r2 = this.DecimalDigits(ref cursor);
                    if (r2 != null)
                    {
                        IParseResult<IList<string>> r3 = null;
                        var startCursor1 = cursor;
                        var l0 = new List<string>();
                        while (l0.Count < 1)
                        {
                            IParseResult<string> r4 = null;
                            var startCursor2 = cursor;
                            IParseResult<string> r5 = null;
                            r5 = this.ParseLiteral(ref cursor, ",");
                            if (r5 != null)
                            {
                                IParseResult<IList<IList<string>>> r6 = null;
                                var startCursor3 = cursor;
                                var l1 = new List<IList<string>>();
                                while (l1.Count < 1)
                                {
                                    IParseResult<IList<string>> r7 = null;
                                    r7 = this.DecimalDigits(ref cursor);
                                    if (r7 != null)
                                    {
                                        l1.Add(r7.Value);
                                    }
                                    else
                                    {
                                        break;
                                    }
                                }
                                if (l1.Count >= 0)
                                {
                                    r6 = new ParseResult<IList<IList<string>>>(startCursor3, cursor, l1.AsReadOnly());
                                }
                                else
                                {
                                    cursor = startCursor3;
                                }
                                if (r6 != null)
                                {
                                    var len = cursor.Location - startCursor2.Location;
                                    r4 = new ParseResult<string>(startCursor2, cursor, cursor.Subject.Substring(startCursor2.Location, len));
                                }
                                else
                                {
                                    cursor = startCursor2;
                                }
                            }
                            else
                            {
                                cursor = startCursor2;
                            }
                            if (r4 != null)
                            {
                                l0.Add(r4.Value);
                            }
                            else
                            {
                                break;
                            }
                        }
                        if (l0.Count >= 0)
                        {
                            r3 = new ParseResult<IList<string>>(startCursor1, cursor, l0.AsReadOnly());
                        }
                        else
                        {
                            cursor = startCursor1;
                        }
                        if (r3 != null)
                        {
                            IParseResult<string> r8 = null;
                            r8 = this.ParseLiteral(ref cursor, "}");
                            if (r8 != null)
                            {
                                var len = cursor.Location - startCursor0.Location;
                                r0 = new ParseResult<string>(startCursor0, cursor, cursor.Subject.Substring(startCursor0.Location, len));
                            }
                            else
                            {
                                cursor = startCursor0;
                            }
                        }
                        else
                        {
                            cursor = startCursor0;
                        }
                    }
                    else
                    {
                        cursor = startCursor0;
                    }
                }
                else
                {
                    cursor = startCursor0;
                }
            }
            return r0;
        }

        private IParseResult<string> Atom(ref Cursor cursor)
        {
            IParseResult<string> r0 = null;
            if (r0 == null)
            {
                r0 = this.PatternCharacter(ref cursor);
            }
            if (r0 == null)
            {
                r0 = this.ParseLiteral(ref cursor, ".");
            }
            if (r0 == null)
            {
                var startCursor0 = cursor;
                IParseResult<string> r1 = null;
                r1 = this.ParseLiteral(ref cursor, "\\");
                if (r1 != null)
                {
                    IParseResult<string> r2 = null;
                    r2 = this.AtomEscape(ref cursor);
                    if (r2 != null)
                    {
                        var len = cursor.Location - startCursor0.Location;
                        r0 = new ParseResult<string>(startCursor0, cursor, cursor.Subject.Substring(startCursor0.Location, len));
                    }
                    else
                    {
                        cursor = startCursor0;
                    }
                }
                else
                {
                    cursor = startCursor0;
                }
            }
            if (r0 == null)
            {
                r0 = this.CharacterClass(ref cursor);
            }
            if (r0 == null)
            {
                var startCursor1 = cursor;
                IParseResult<string> r3 = null;
                r3 = this.ParseLiteral(ref cursor, "(");
                if (r3 != null)
                {
                    IParseResult<string> r4 = null;
                    r4 = this.Disjunction(ref cursor);
                    if (r4 != null)
                    {
                        IParseResult<string> r5 = null;
                        r5 = this.ParseLiteral(ref cursor, ")");
                        if (r5 != null)
                        {
                            var len = cursor.Location - startCursor1.Location;
                            r0 = new ParseResult<string>(startCursor1, cursor, cursor.Subject.Substring(startCursor1.Location, len));
                        }
                        else
                        {
                            cursor = startCursor1;
                        }
                    }
                    else
                    {
                        cursor = startCursor1;
                    }
                }
                else
                {
                    cursor = startCursor1;
                }
            }
            if (r0 == null)
            {
                var startCursor2 = cursor;
                IParseResult<string> r6 = null;
                r6 = this.ParseLiteral(ref cursor, "(?:");
                if (r6 != null)
                {
                    IParseResult<string> r7 = null;
                    r7 = this.Disjunction(ref cursor);
                    if (r7 != null)
                    {
                        IParseResult<string> r8 = null;
                        r8 = this.ParseLiteral(ref cursor, ")");
                        if (r8 != null)
                        {
                            var len = cursor.Location - startCursor2.Location;
                            r0 = new ParseResult<string>(startCursor2, cursor, cursor.Subject.Substring(startCursor2.Location, len));
                        }
                        else
                        {
                            cursor = startCursor2;
                        }
                    }
                    else
                    {
                        cursor = startCursor2;
                    }
                }
                else
                {
                    cursor = startCursor2;
                }
            }
            return r0;
        }

        private IParseResult<string> PatternCharacter(ref Cursor cursor)
        {
            IParseResult<string> r0 = null;
            var startCursor0 = cursor;
            IParseResult<string> r1 = null;
            var startCursor1 = cursor;
            IParseResult<string> r2 = null;
            r2 = this.ParseClass(ref cursor, "^^$$\\\\..**++??(())[[]]{{}}||");
            cursor = startCursor1;
            if (r2 == null)
            {
                r1 = new ParseResult<string>(cursor, cursor, string.Empty);
            }
            if (r1 != null)
            {
                IParseResult<string> r3 = null;
                r3 = this.SourceCharacter(ref cursor);
                if (r3 != null)
                {
                    var len = cursor.Location - startCursor0.Location;
                    r0 = new ParseResult<string>(startCursor0, cursor, cursor.Subject.Substring(startCursor0.Location, len));
                }
                else
                {
                    cursor = startCursor0;
                }
            }
            else
            {
                cursor = startCursor0;
            }
            return r0;
        }

        private IParseResult<string> AtomEscape(ref Cursor cursor)
        {
            IParseResult<string> r0 = null;
            if (r0 == null)
            {
                r0 = this.DecimalEscape(ref cursor);
            }
            if (r0 == null)
            {
                r0 = this.CharacterEscape(ref cursor);
            }
            if (r0 == null)
            {
                r0 = this.CharacterClassEscape(ref cursor);
            }
            return r0;
        }

        private IParseResult<string> CharacterEscape(ref Cursor cursor)
        {
            IParseResult<string> r0 = null;
            if (r0 == null)
            {
                r0 = this.ControlEscape(ref cursor);
            }
            if (r0 == null)
            {
                var startCursor0 = cursor;
                IParseResult<string> r1 = null;
                r1 = this.ParseLiteral(ref cursor, "c");
                if (r1 != null)
                {
                    IParseResult<string> r2 = null;
                    r2 = this.ControlLetter(ref cursor);
                    if (r2 != null)
                    {
                        var len = cursor.Location - startCursor0.Location;
                        r0 = new ParseResult<string>(startCursor0, cursor, cursor.Subject.Substring(startCursor0.Location, len));
                    }
                    else
                    {
                        cursor = startCursor0;
                    }
                }
                else
                {
                    cursor = startCursor0;
                }
            }
            if (r0 == null)
            {
                r0 = this.HexEscapeSequence(ref cursor);
            }
            if (r0 == null)
            {
                r0 = this.UnicodeEscapeSequence(ref cursor);
            }
            if (r0 == null)
            {
                r0 = this.IdentityEscape(ref cursor);
            }
            return r0;
        }

        private IParseResult<string> ControlEscape(ref Cursor cursor)
        {
            IParseResult<string> r0 = null;
            r0 = this.ParseClass(ref cursor, "ffnnrrttvv");
            return r0;
        }

        private IParseResult<string> ControlLetter(ref Cursor cursor)
        {
            IParseResult<string> r0 = null;
            r0 = this.ParseClass(ref cursor, "azAZ");
            return r0;
        }

        private IParseResult<string> IdentityEscape(ref Cursor cursor)
        {
            IParseResult<string> r0 = null;
            if (r0 == null)
            {
                var startCursor0 = cursor;
                IParseResult<string> r1 = null;
                var startCursor1 = cursor;
                IParseResult<string> r2 = null;
                r2 = this.IdentifierPart(ref cursor);
                cursor = startCursor1;
                if (r2 == null)
                {
                    r1 = new ParseResult<string>(cursor, cursor, string.Empty);
                }
                if (r1 != null)
                {
                    IParseResult<string> r3 = null;
                    r3 = this.SourceCharacter(ref cursor);
                    if (r3 != null)
                    {
                        var len = cursor.Location - startCursor0.Location;
                        r0 = new ParseResult<string>(startCursor0, cursor, cursor.Subject.Substring(startCursor0.Location, len));
                    }
                    else
                    {
                        cursor = startCursor0;
                    }
                }
                else
                {
                    cursor = startCursor0;
                }
            }
            if (r0 == null)
            {
                r0 = this.ParseLiteral(ref cursor, "\u200d");
            }
            if (r0 == null)
            {
                r0 = this.ParseLiteral(ref cursor, "\u200c");
            }
            return r0;
        }

        private IParseResult<string> DecimalEscape(ref Cursor cursor)
        {
            IParseResult<string> r0 = null;
            var startCursor0 = cursor;
            IParseResult<string> r1 = null;
            r1 = this.DecimalIntegerLiteral(ref cursor);
            if (r1 != null)
            {
                IParseResult<string> r2 = null;
                var startCursor1 = cursor;
                IParseResult<string> r3 = null;
                r3 = this.DecimalDigit(ref cursor);
                cursor = startCursor1;
                if (r3 == null)
                {
                    r2 = new ParseResult<string>(cursor, cursor, string.Empty);
                }
                if (r2 != null)
                {
                    var len = cursor.Location - startCursor0.Location;
                    r0 = new ParseResult<string>(startCursor0, cursor, cursor.Subject.Substring(startCursor0.Location, len));
                }
                else
                {
                    cursor = startCursor0;
                }
            }
            else
            {
                cursor = startCursor0;
            }
            return r0;
        }

        private IParseResult<string> CharacterClassEscape(ref Cursor cursor)
        {
            IParseResult<string> r0 = null;
            r0 = this.ParseClass(ref cursor, "ddDDssSSwwWW");
            return r0;
        }

        private IParseResult<string> CharacterClass(ref Cursor cursor)
        {
            IParseResult<string> r0 = null;
            if (r0 == null)
            {
                var startCursor0 = cursor;
                IParseResult<string> r1 = null;
                r1 = this.ParseLiteral(ref cursor, "[");
                if (r1 != null)
                {
                    IParseResult<string> r2 = null;
                    var startCursor1 = cursor;
                    IParseResult<string> r3 = null;
                    r3 = this.ParseLiteral(ref cursor, "^");
                    cursor = startCursor1;
                    if (r3 == null)
                    {
                        r2 = new ParseResult<string>(cursor, cursor, string.Empty);
                    }
                    if (r2 != null)
                    {
                        IParseResult<IList<string>> r4 = null;
                        r4 = this.ClassRanges(ref cursor);
                        if (r4 != null)
                        {
                            IParseResult<string> r5 = null;
                            r5 = this.ParseLiteral(ref cursor, "]");
                            if (r5 != null)
                            {
                                var len = cursor.Location - startCursor0.Location;
                                r0 = new ParseResult<string>(startCursor0, cursor, cursor.Subject.Substring(startCursor0.Location, len));
                            }
                            else
                            {
                                cursor = startCursor0;
                            }
                        }
                        else
                        {
                            cursor = startCursor0;
                        }
                    }
                    else
                    {
                        cursor = startCursor0;
                    }
                }
                else
                {
                    cursor = startCursor0;
                }
            }
            if (r0 == null)
            {
                var startCursor2 = cursor;
                IParseResult<string> r6 = null;
                r6 = this.ParseLiteral(ref cursor, "[^");
                if (r6 != null)
                {
                    IParseResult<IList<string>> r7 = null;
                    r7 = this.ClassRanges(ref cursor);
                    if (r7 != null)
                    {
                        IParseResult<string> r8 = null;
                        r8 = this.ParseLiteral(ref cursor, "]");
                        if (r8 != null)
                        {
                            var len = cursor.Location - startCursor2.Location;
                            r0 = new ParseResult<string>(startCursor2, cursor, cursor.Subject.Substring(startCursor2.Location, len));
                        }
                        else
                        {
                            cursor = startCursor2;
                        }
                    }
                    else
                    {
                        cursor = startCursor2;
                    }
                }
                else
                {
                    cursor = startCursor2;
                }
            }
            return r0;
        }

        private IParseResult<IList<string>> ClassRanges(ref Cursor cursor)
        {
            IParseResult<IList<string>> r0 = null;
            var startCursor0 = cursor;
            var l0 = new List<string>();
            while (l0.Count < 1)
            {
                IParseResult<string> r1 = null;
                r1 = this.NonemptyClassRanges(ref cursor);
                if (r1 != null)
                {
                    l0.Add(r1.Value);
                }
                else
                {
                    break;
                }
            }
            if (l0.Count >= 0)
            {
                r0 = new ParseResult<IList<string>>(startCursor0, cursor, l0.AsReadOnly());
            }
            else
            {
                cursor = startCursor0;
            }
            return r0;
        }

        private IParseResult<string> NonemptyClassRanges(ref Cursor cursor)
        {
            IParseResult<string> r0 = null;
            if (r0 == null)
            {
                var startCursor0 = cursor;
                IParseResult<string> r1 = null;
                r1 = this.ClassAtom(ref cursor);
                if (r1 != null)
                {
                    IParseResult<string> r2 = null;
                    r2 = this.ParseLiteral(ref cursor, "-");
                    if (r2 != null)
                    {
                        IParseResult<string> r3 = null;
                        r3 = this.ClassAtom(ref cursor);
                        if (r3 != null)
                        {
                            IParseResult<IList<string>> r4 = null;
                            r4 = this.ClassRanges(ref cursor);
                            if (r4 != null)
                            {
                                var len = cursor.Location - startCursor0.Location;
                                r0 = new ParseResult<string>(startCursor0, cursor, cursor.Subject.Substring(startCursor0.Location, len));
                            }
                            else
                            {
                                cursor = startCursor0;
                            }
                        }
                        else
                        {
                            cursor = startCursor0;
                        }
                    }
                    else
                    {
                        cursor = startCursor0;
                    }
                }
                else
                {
                    cursor = startCursor0;
                }
            }
            if (r0 == null)
            {
                var startCursor1 = cursor;
                IParseResult<string> r5 = null;
                r5 = this.ClassAtom(ref cursor);
                if (r5 != null)
                {
                    IParseResult<string> r6 = null;
                    r6 = this.NonemptyClassRangesNoDash(ref cursor);
                    if (r6 != null)
                    {
                        var len = cursor.Location - startCursor1.Location;
                        r0 = new ParseResult<string>(startCursor1, cursor, cursor.Subject.Substring(startCursor1.Location, len));
                    }
                    else
                    {
                        cursor = startCursor1;
                    }
                }
                else
                {
                    cursor = startCursor1;
                }
            }
            if (r0 == null)
            {
                r0 = this.ClassAtom(ref cursor);
            }
            return r0;
        }

        private IParseResult<string> NonemptyClassRangesNoDash(ref Cursor cursor)
        {
            IParseResult<string> r0 = null;
            if (r0 == null)
            {
                var startCursor0 = cursor;
                IParseResult<string> r1 = null;
                r1 = this.ClassAtomNoDash(ref cursor);
                if (r1 != null)
                {
                    IParseResult<string> r2 = null;
                    r2 = this.ParseLiteral(ref cursor, "-");
                    if (r2 != null)
                    {
                        IParseResult<string> r3 = null;
                        r3 = this.ClassAtom(ref cursor);
                        if (r3 != null)
                        {
                            IParseResult<IList<string>> r4 = null;
                            r4 = this.ClassRanges(ref cursor);
                            if (r4 != null)
                            {
                                var len = cursor.Location - startCursor0.Location;
                                r0 = new ParseResult<string>(startCursor0, cursor, cursor.Subject.Substring(startCursor0.Location, len));
                            }
                            else
                            {
                                cursor = startCursor0;
                            }
                        }
                        else
                        {
                            cursor = startCursor0;
                        }
                    }
                    else
                    {
                        cursor = startCursor0;
                    }
                }
                else
                {
                    cursor = startCursor0;
                }
            }
            if (r0 == null)
            {
                var startCursor1 = cursor;
                IParseResult<string> r5 = null;
                r5 = this.ClassAtomNoDash(ref cursor);
                if (r5 != null)
                {
                    IParseResult<string> r6 = null;
                    r6 = this.NonemptyClassRangesNoDash(ref cursor);
                    if (r6 != null)
                    {
                        var len = cursor.Location - startCursor1.Location;
                        r0 = new ParseResult<string>(startCursor1, cursor, cursor.Subject.Substring(startCursor1.Location, len));
                    }
                    else
                    {
                        cursor = startCursor1;
                    }
                }
                else
                {
                    cursor = startCursor1;
                }
            }
            if (r0 == null)
            {
                r0 = this.ClassAtom(ref cursor);
            }
            return r0;
        }

        private IParseResult<string> ClassAtom(ref Cursor cursor)
        {
            IParseResult<string> r0 = null;
            if (r0 == null)
            {
                r0 = this.ParseLiteral(ref cursor, "-");
            }
            if (r0 == null)
            {
                r0 = this.ClassAtomNoDash(ref cursor);
            }
            return r0;
        }

        private IParseResult<string> ClassAtomNoDash(ref Cursor cursor)
        {
            IParseResult<string> r0 = null;
            if (r0 == null)
            {
                var startCursor0 = cursor;
                IParseResult<string> r1 = null;
                var startCursor1 = cursor;
                IParseResult<string> r2 = null;
                r2 = this.ParseClass(ref cursor, "\\\\]]--");
                cursor = startCursor1;
                if (r2 == null)
                {
                    r1 = new ParseResult<string>(cursor, cursor, string.Empty);
                }
                if (r1 != null)
                {
                    IParseResult<string> r3 = null;
                    r3 = this.SourceCharacter(ref cursor);
                    if (r3 != null)
                    {
                        var len = cursor.Location - startCursor0.Location;
                        r0 = new ParseResult<string>(startCursor0, cursor, cursor.Subject.Substring(startCursor0.Location, len));
                    }
                    else
                    {
                        cursor = startCursor0;
                    }
                }
                else
                {
                    cursor = startCursor0;
                }
            }
            if (r0 == null)
            {
                var startCursor2 = cursor;
                IParseResult<string> r4 = null;
                r4 = this.ParseLiteral(ref cursor, "\\");
                if (r4 != null)
                {
                    IParseResult<string> r5 = null;
                    r5 = this.ClassEscape(ref cursor);
                    if (r5 != null)
                    {
                        var len = cursor.Location - startCursor2.Location;
                        r0 = new ParseResult<string>(startCursor2, cursor, cursor.Subject.Substring(startCursor2.Location, len));
                    }
                    else
                    {
                        cursor = startCursor2;
                    }
                }
                else
                {
                    cursor = startCursor2;
                }
            }
            return r0;
        }

        private IParseResult<string> ClassEscape(ref Cursor cursor)
        {
            IParseResult<string> r0 = null;
            if (r0 == null)
            {
                r0 = this.DecimalEscape(ref cursor);
            }
            if (r0 == null)
            {
                r0 = this.ParseLiteral(ref cursor, "b");
            }
            if (r0 == null)
            {
                r0 = this.CharacterEscape(ref cursor);
            }
            if (r0 == null)
            {
                r0 = this.CharacterClassEscape(ref cursor);
            }
            return r0;
        }

        private IParseResult<string> DecimalDigit(ref Cursor cursor)
        {
            IParseResult<string> r0 = null;
            r0 = this.ParseClass(ref cursor, "09");
            return r0;
        }

        private IParseResult<IList<string>> DecimalDigits(ref Cursor cursor)
        {
            IParseResult<IList<string>> r0 = null;
            var startCursor0 = cursor;
            var l0 = new List<string>();
            while (true)
            {
                IParseResult<string> r1 = null;
                r1 = this.DecimalDigit(ref cursor);
                if (r1 != null)
                {
                    l0.Add(r1.Value);
                }
                else
                {
                    break;
                }
            }
            if (l0.Count >= 1)
            {
                r0 = new ParseResult<IList<string>>(startCursor0, cursor, l0.AsReadOnly());
            }
            else
            {
                cursor = startCursor0;
            }
            return r0;
        }

        private IParseResult<string> SourceCharacter(ref Cursor cursor)
        {
            IParseResult<string> r0 = null;
            r0 = this.ParseAny(ref cursor);
            return r0;
        }

        private IParseResult<string> DecimalIntegerLiteral(ref Cursor cursor)
        {
            IParseResult<string> r0 = null;
            if (r0 == null)
            {
                r0 = this.ParseLiteral(ref cursor, "0");
            }
            if (r0 == null)
            {
                var startCursor0 = cursor;
                IParseResult<string> r1 = null;
                r1 = this.NonZeroDigit(ref cursor);
                if (r1 != null)
                {
                    IParseResult<IList<IList<string>>> r2 = null;
                    var startCursor1 = cursor;
                    var l0 = new List<IList<string>>();
                    while (l0.Count < 1)
                    {
                        IParseResult<IList<string>> r3 = null;
                        r3 = this.DecimalDigits(ref cursor);
                        if (r3 != null)
                        {
                            l0.Add(r3.Value);
                        }
                        else
                        {
                            break;
                        }
                    }
                    if (l0.Count >= 0)
                    {
                        r2 = new ParseResult<IList<IList<string>>>(startCursor1, cursor, l0.AsReadOnly());
                    }
                    else
                    {
                        cursor = startCursor1;
                    }
                    if (r2 != null)
                    {
                        var len = cursor.Location - startCursor0.Location;
                        r0 = new ParseResult<string>(startCursor0, cursor, cursor.Subject.Substring(startCursor0.Location, len));
                    }
                    else
                    {
                        cursor = startCursor0;
                    }
                }
                else
                {
                    cursor = startCursor0;
                }
            }
            return r0;
        }

        private IParseResult<string> HexEscapeSequence(ref Cursor cursor)
        {
            IParseResult<string> r0 = null;
            var startCursor0 = cursor;
            IParseResult<string> r1 = null;
            r1 = this.ParseLiteral(ref cursor, "x");
            if (r1 != null)
            {
                IParseResult<string> r2 = null;
                r2 = this.HexDigit(ref cursor);
                if (r2 != null)
                {
                    IParseResult<string> r3 = null;
                    r3 = this.HexDigit(ref cursor);
                    if (r3 != null)
                    {
                        var len = cursor.Location - startCursor0.Location;
                        r0 = new ParseResult<string>(startCursor0, cursor, cursor.Subject.Substring(startCursor0.Location, len));
                    }
                    else
                    {
                        cursor = startCursor0;
                    }
                }
                else
                {
                    cursor = startCursor0;
                }
            }
            else
            {
                cursor = startCursor0;
            }
            return r0;
        }

        private IParseResult<string> UnicodeEscapeSequence(ref Cursor cursor)
        {
            IParseResult<string> r0 = null;
            var startCursor0 = cursor;
            IParseResult<string> r1 = null;
            r1 = this.ParseLiteral(ref cursor, "u");
            if (r1 != null)
            {
                IParseResult<string> r2 = null;
                r2 = this.HexDigit(ref cursor);
                if (r2 != null)
                {
                    IParseResult<string> r3 = null;
                    r3 = this.HexDigit(ref cursor);
                    if (r3 != null)
                    {
                        IParseResult<string> r4 = null;
                        r4 = this.HexDigit(ref cursor);
                        if (r4 != null)
                        {
                            IParseResult<string> r5 = null;
                            r5 = this.HexDigit(ref cursor);
                            if (r5 != null)
                            {
                                var len = cursor.Location - startCursor0.Location;
                                r0 = new ParseResult<string>(startCursor0, cursor, cursor.Subject.Substring(startCursor0.Location, len));
                            }
                            else
                            {
                                cursor = startCursor0;
                            }
                        }
                        else
                        {
                            cursor = startCursor0;
                        }
                    }
                    else
                    {
                        cursor = startCursor0;
                    }
                }
                else
                {
                    cursor = startCursor0;
                }
            }
            else
            {
                cursor = startCursor0;
            }
            return r0;
        }

        private IParseResult<string> NonZeroDigit(ref Cursor cursor)
        {
            IParseResult<string> r0 = null;
            r0 = this.ParseClass(ref cursor, "19");
            return r0;
        }

        private IParseResult<string> HexDigit(ref Cursor cursor)
        {
            IParseResult<string> r0 = null;
            r0 = this.ParseClass(ref cursor, "09afAF");
            return r0;
        }

        private IParseResult<string> IdentifierPart(ref Cursor cursor)
        {
            IParseResult<string> r0 = null;
            if (r0 == null)
            {
                r0 = this.IdentifierStart(ref cursor);
            }
            if (r0 == null)
            {
                r0 = this.UnicodeCombiningMark(ref cursor);
            }
            if (r0 == null)
            {
                r0 = this.UnicodeDigit(ref cursor);
            }
            if (r0 == null)
            {
                r0 = this.UnicodeConnectorPunctuation(ref cursor);
            }
            if (r0 == null)
            {
                r0 = this.ParseLiteral(ref cursor, "\u200d");
            }
            if (r0 == null)
            {
                r0 = this.ParseLiteral(ref cursor, "\u200c");
            }
            return r0;
        }

        private IParseResult<string> IdentifierStart(ref Cursor cursor)
        {
            IParseResult<string> r0 = null;
            if (r0 == null)
            {
                r0 = this.UnicodeLetter(ref cursor);
            }
            if (r0 == null)
            {
                r0 = this.ParseLiteral(ref cursor, "$");
            }
            if (r0 == null)
            {
                r0 = this.ParseLiteral(ref cursor, "_");
            }
            if (r0 == null)
            {
                var startCursor0 = cursor;
                IParseResult<string> r1 = null;
                r1 = this.ParseLiteral(ref cursor, "\\");
                if (r1 != null)
                {
                    IParseResult<string> r2 = null;
                    r2 = this.UnicodeEscapeSequence(ref cursor);
                    if (r2 != null)
                    {
                        var len = cursor.Location - startCursor0.Location;
                        r0 = new ParseResult<string>(startCursor0, cursor, cursor.Subject.Substring(startCursor0.Location, len));
                    }
                    else
                    {
                        cursor = startCursor0;
                    }
                }
                else
                {
                    cursor = startCursor0;
                }
            }
            return r0;
        }

        private IParseResult<string> UnicodeLetter(ref Cursor cursor)
        {
            IParseResult<string> r0 = null;
            var startCursor0 = cursor;
            IParseResult<string> r1 = null;
            var charStart = cursor;
            r1 = this.ParseAny(ref cursor);
            var charEnd = cursor;
            var @char = ValueOrDefault(r1);
            if (r1 != null)
            {
                IParseResult<string> r2 = null;
                if ( unicodeLetterCategories.Contains(char.GetUnicodeCategory(@char[0])) )
                {
                    r2 = new ParseResult<string>(cursor, cursor, string.Empty);
                }
                if (r2 != null)
                {
                    var len = cursor.Location - startCursor0.Location;
                    r0 = new ParseResult<string>(startCursor0, cursor, cursor.Subject.Substring(startCursor0.Location, len));
                }
                else
                {
                    cursor = startCursor0;
                }
            }
            else
            {
                cursor = startCursor0;
            }
            return r0;
        }

        private IParseResult<string> UnicodeCombiningMark(ref Cursor cursor)
        {
            IParseResult<string> r0 = null;
            var startCursor0 = cursor;
            IParseResult<string> r1 = null;
            var charStart = cursor;
            r1 = this.ParseAny(ref cursor);
            var charEnd = cursor;
            var @char = ValueOrDefault(r1);
            if (r1 != null)
            {
                IParseResult<string> r2 = null;
                if ( unicodeCombiningMarkCategories.Contains(char.GetUnicodeCategory(@char[0])) )
                {
                    r2 = new ParseResult<string>(cursor, cursor, string.Empty);
                }
                if (r2 != null)
                {
                    var len = cursor.Location - startCursor0.Location;
                    r0 = new ParseResult<string>(startCursor0, cursor, cursor.Subject.Substring(startCursor0.Location, len));
                }
                else
                {
                    cursor = startCursor0;
                }
            }
            else
            {
                cursor = startCursor0;
            }
            return r0;
        }

        private IParseResult<string> UnicodeDigit(ref Cursor cursor)
        {
            IParseResult<string> r0 = null;
            var startCursor0 = cursor;
            IParseResult<string> r1 = null;
            var charStart = cursor;
            r1 = this.ParseAny(ref cursor);
            var charEnd = cursor;
            var @char = ValueOrDefault(r1);
            if (r1 != null)
            {
                IParseResult<string> r2 = null;
                if ( unicodeDigitCategories.Contains(char.GetUnicodeCategory(@char[0])) )
                {
                    r2 = new ParseResult<string>(cursor, cursor, string.Empty);
                }
                if (r2 != null)
                {
                    var len = cursor.Location - startCursor0.Location;
                    r0 = new ParseResult<string>(startCursor0, cursor, cursor.Subject.Substring(startCursor0.Location, len));
                }
                else
                {
                    cursor = startCursor0;
                }
            }
            else
            {
                cursor = startCursor0;
            }
            return r0;
        }

        private IParseResult<string> UnicodeConnectorPunctuation(ref Cursor cursor)
        {
            IParseResult<string> r0 = null;
            var startCursor0 = cursor;
            IParseResult<string> r1 = null;
            var charStart = cursor;
            r1 = this.ParseAny(ref cursor);
            var charEnd = cursor;
            var @char = ValueOrDefault(r1);
            if (r1 != null)
            {
                IParseResult<string> r2 = null;
                if ( unicodeConnectorPunctuationCategories.Contains(char.GetUnicodeCategory(@char[0])) )
                {
                    r2 = new ParseResult<string>(cursor, cursor, string.Empty);
                }
                if (r2 != null)
                {
                    var len = cursor.Location - startCursor0.Location;
                    r0 = new ParseResult<string>(startCursor0, cursor, cursor.Subject.Substring(startCursor0.Location, len));
                }
                else
                {
                    cursor = startCursor0;
                }
            }
            else
            {
                cursor = startCursor0;
            }
            return r0;
        }

        private IParseResult<string> ParseLiteral(ref Cursor cursor, string literal, bool ignoreCase = false)
        {
            if (cursor.Location + literal.Length <= cursor.Subject.Length)
            {
                var substr = cursor.Subject.Substring(cursor.Location, literal.Length);
                if (ignoreCase ? substr.Equals(literal, StringComparison.OrdinalIgnoreCase) : substr == literal)
                {
                    var endCursor = cursor.Advance(substr.Length);
                    var result = new ParseResult<string>(cursor, endCursor, substr);
                    cursor = endCursor;
                    return result;
                }
            }
            return null;
        }

        private IParseResult<string> ParseClass(ref Cursor cursor, string characterRanges, bool negated = false, bool ignoreCase = false)
        {
            if (cursor.Location + 1 <= cursor.Subject.Length)
            {
                var c = cursor.Subject[cursor.Location];
                bool match = false;
                for (int i = 0; !match && i < characterRanges.Length; i += 2)
                {
                    match = c >= characterRanges[i] && c <= characterRanges[i + 1];
                }
                if (!match && ignoreCase && (char.IsUpper(c) || char.IsLower(c)))
                {
                    var cs = c.ToString();
                    for (int i = 0; !match && i < characterRanges.Length; i += 2)
                    {
                        var min = characterRanges[i];
                        var max = characterRanges[i + 1];
                        for (char o = min; !match && o <= max; o++)
                        {
                            match = (char.IsUpper(o) || char.IsLower(o)) && cs.Equals(o.ToString(), StringComparison.CurrentCultureIgnoreCase);
                        }
                    }
                }
                if (match ^ negated)
                {
                    var endCursor = cursor.Advance(1);
                    var result = new ParseResult<string>(cursor, endCursor, cursor.Subject.Substring(cursor.Location, 1));
                    cursor = endCursor;
                    return result;
                }
            }
            return null;
        }

        private IParseResult<string> ParseAny(ref Cursor cursor)
        {
            if (cursor.Location + 1 <= cursor.Subject.Length)
            {
                var substr = cursor.Subject.Substring(cursor.Location, 1);
                var endCursor = cursor.Advance(1);
                var result = new ParseResult<string>(cursor, endCursor, substr);
                cursor = endCursor;
                return result;
            }
            return null;
        }

        private IParseResult<T> ReturnHelper<T>(Cursor startCursor, Cursor endCursor, Func<T> wrappedCode)
        {
            return new ParseResult<T>(startCursor, endCursor, wrappedCode());
        }

        private Exception ExceptionHelper(Cursor cursor, Func<string> wrappedCode)
        {
            var ex = new FormatException(wrappedCode());
            ex.Data["cursor"] = cursor;
            return ex;
        }

        private T ValueOrDefault<T>(IParseResult<T> result)
        {
            return result == null
                ? default(T)
                : result.Value;
        }
    }
}
